services:
    command_bus:
        alias: matthias_simple_bus.finishes_command_before_handling_next

    matthias_simple_bus.delegating_command_bus:
        class: Matthias\SimpleBus\Command\DelegatesToCommandHandlers
        public: false
        arguments:
            - @service_container
            # collection of command handler services, will be populated using RegisterHandlerPass
            - []
        tags:
            - { name: command_bus, priority: -1000 }

    matthias_simple_bus.finishes_command_before_handling_next:
        class: Matthias\SimpleBus\Command\FinishesCommandBeforeHandlingNext
        public: false
        tags:
            - { name: command_bus, priority: 1000 }
