services:
    # override this alias to use a different entity manager
    matthias_doctrine_orm_event_bus_bridge.entity_manager:
        alias: doctrine.orm.entity_manager
        public: false

    matthias_doctrine_orm_event_bus_bridge.wraps_next_command_in_transaction:
        class: Matthias\SimpleBus\DoctrineORM\WrapsNextCommandInTransaction
        public: false
        arguments:
            - @matthias_doctrine_orm_event_bus_bridge.entity_manager
        tags:
            - { name: command_bus, priority: 100 }

    matthias_doctrine_orm_event_bus_bridge.collects_event_providing_entities:
        class: Matthias\SimpleBus\DoctrineORM\CollectsEventProvidingEntities
        public: false
        tags:
            - { name: doctrine.event_subscriber }
            - { name: event_provider_collector }
