services:
    matthias_event_bus.events.finishes_event_before_handling_next:
        class: Matthias\SimpleBus\Event\FinishesEventBeforeHandlingNext
        public: false

    matthias_event_bus.aggregates_multiple_event_provider_collectors:
        class: Matthias\SimpleBus\Event\Provider\AggregatesMultipleEventProviderCollectors
        arguments:
            # collection of CollectsEventProviders, will be populated using RegisterEventProviderCollectors
            - []

    matthias_event_bus.delegates_to_event_handlers:
        class: Matthias\SimpleBus\Event\Handler\DelegatesToEventHandlers
        arguments:
            - @matthias_event_bus.event_handlers_resolver
        tags:
            - { name: event_bus }

    matthias_event_bus.event_handlers_resolver:
        class: Matthias\SimpleBus\Event\Handler\LazyLoadingEventHandlersResolver
        public: false
        arguments:
            - @matthias_event_bus.invokable_service_locator
            # collection of event handler services ids, will be populated using RegisterHandlers
            - []

    matthias_event_bus.invokable_service_locator:
        class: Matthias\SimpleBus\SymfonyBundle\DependencyInjection\InvokableServiceLocator
        public: false
        arguments:
            - @service_container

    matthias_event_bus.event_dispatching_command_bus:
        class: Matthias\SimpleBus\Event\CommandBus\DispatchesEvents
        public: false
        arguments:
            - @matthias_event_bus.aggregates_multiple_event_provider_collectors
            - @matthias_event_bus.delegates_to_event_handlers
        tags:
            - { name: command_bus, priority: 200 }
